name: 📦🚀 Build Installer - Linux TAR.GZ AMD64

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    tags:
      - '**'
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/release/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    name: Linux amd64 tar.gz archive
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
    
    - name: Build execution client
      run: go run build/ci.go install -static
      env:
        GO111MODULE: on
    
    - name: Build archive
      run: go run build/ci.go archive -type tar
      env:
        GO111MODULE: on

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bpx-installers-linux-intel
        path: ${{ github.workspace }}/bpx-execution-client-*.tar.gz

    - name: Upload release artifacts
      if: github.event_name == 'release'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload \
          ${GITHUB_REF#refs/*/} \
          bpx-execution-client-*.tar.gz
